<?php

declare(strict_types=1);

namespace App\Core\Plugin\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Str;

/**
 * Pre-Production Readiness: a genuinely minimal scaffold generator — not a
 * second SDK. It writes exactly the same real shape already proven by the
 * `plugins/hello-world-plugin` fixture (plugin.json, composer.json, a
 * ServiceProvider extending the real App\Core\Plugin\PluginServiceProvider)
 * and nothing more. See docs/plugins/example-plugin-guide.md for how to add
 * navigation, routes, migrations, etc. to the generated scaffold.
 */
class PluginMakeCommand extends Command
{
    protected $signature = 'plugin:make {id : The plugin id, kebab-case (e.g. acme-example-plugin)}';

    protected $description = 'Scaffold a minimal, valid plugin package (mirrors the hello-world-plugin fixture shape)';

    public function handle(): int
    {
        $id = Str::kebab((string) $this->argument('id'));
        $path = base_path("plugins/{$id}");

        if (is_dir($path)) {
            $this->error("plugins/{$id} already exists.");

            return self::FAILURE;
        }

        $studly = Str::studly(str_replace('-', '_', $id));
        $namespace = 'Plugins\\'.$studly;
        $providerClass = "{$studly}ServiceProvider";

        mkdir($path.'/src', 0755, true);

        file_put_contents($path.'/plugin.json', json_encode([
            'manifest_version' => 1,
            'id' => $id,
            'name' => Str::headline($id),
            'version' => '1.0.0',
            'author' => 'Your Name',
            'license' => 'MIT',
            'description' => 'Describe what this plugin does.',
            'compatibility' => ['platform' => '*', 'php' => '^8.4'],
            'dependencies' => new \stdClass,
            'requested_permissions' => [],
            'capabilities' => [],
            'entrypoint' => "{$namespace}\\{$providerClass}",
            'namespace' => $namespace,
            'migrations' => 'database/migrations',
            'settings_schema' => new \stdClass,
        ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)."\n");

        file_put_contents($path.'/composer.json', json_encode([
            'name' => "hyperstore/{$id}",
            'description' => "HyperStore plugin: {$id}.",
            'type' => 'project',
            'license' => 'MIT',
            'autoload' => ['psr-4' => ["{$namespace}\\" => 'src/']],
            'require' => ['php' => '^8.4'],
            'config' => ['vendor-dir' => 'vendor'],
        ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)."\n");

        file_put_contents($path."/src/{$providerClass}.php", <<<PHP
        <?php

        declare(strict_types=1);

        namespace {$namespace};

        use App\Core\Plugin\PluginServiceProvider;

        /**
         * Generated by `php artisan plugin:make {$id}`.
         * See docs/plugins/example-plugin-guide.md for how to register
         * navigation, routes, migrations, and permissions.
         */
        class {$providerClass} extends PluginServiceProvider
        {
            public function boot(): void
            {
                //
            }
        }

        PHP);

        $this->info("Created plugins/{$id} (id={$id}, namespace={$namespace}).");
        $this->line('Next: cd plugins/'.$id.' && composer install (generates vendor/autoload.php required by the Plugin Kernel).');
        $this->line('See docs/plugins/example-plugin-guide.md for adding navigation, routes, and permissions.');

        return self::SUCCESS;
    }
}
